name: Reusable CI Docker

on:
  workflow_call:
    outputs:
      image_ref:
        description: Imagen construida y publicada
        value: ${{ jobs.docker.outputs.image_ref }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_ref: ${{ steps.meta.outputs.image_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set short SHA
        id: meta
        run: |
          TAG=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE_REF="ghcr.io/${GITHUB_REPOSITORY_OWNER}/pin-app:${TAG}"
          echo "image_ref=${IMAGE_REF}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.image_ref }}
