name: Destroy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Escribe DESTROY para eliminar toda la infraestructura"
        required: true
        type: string

jobs:
  destroy:
    name: Terraform Destroy AWS
    runs-on: ubuntu-latest
    #environment:
    #  name: production-destroy
    if: github.event.inputs.confirm_destroy == 'DESTROY'

    defaults:
      run:
        working-directory: terraform/aws

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -input=false -auto-approve
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.ADMIN_PASSWORD }}
          TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }}
          TF_VAR_project_name: ${{ secrets.EC2_PROJECT_NAME }}